version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

    labels: []

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

    labels: []
